# Base Informations about Web Site
title: Marko Idžan
email: marko@idzan.eu
description: Marko Idžan's Official Web Site and Blog
baseurl: 
url: "https://idzan.eu"

# Markdown Details
markdown: kramdown

# Plugins
plugins:
  - jekyll-pwa-plugin
  - jekyll-email-protect
  - jekyll-analytics
  - jekyll-last-modified-at


# Portfolio Collections
collections:
  portfolio:
    output: true

# PWA Configration
pwa:
  sw_src_filepath: service-worker.js
  sw_dest_filename: service-worker.js
  dest_js_directory: assets/js
  precache_recent_posts_num: 5
  precache_glob_directory:
  precache_glob_patterns:
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
    - about.html
    - contact.html
    - blog.html
  precache_glob_ignores:
    - sw-register.js
    - "fonts/**/*"

# Analytics Configuration
jekyll_analytics:
  GoogleAnalytics:
    id: UA-47485892-10
    anonymizeIp: true