title: Marko Idzan
email: marko@idzan.eu
description: Marko Idžan's Official Web Site and Blog
baseurl: 
url: "https://idzan.eu"
permalink: /:title/
markdown: kramdown

collections:
  projects:
    output: true

logo: /assets/img/logos/MarkoIdzan.jpg
lang: en_US

facebook:
  publisher: Idzan.Marko.Official

twitter:
  username: idzanmarko
  card: summary

social:
  name: Marko Idzan
  links:
    - https://facebook.com/Idzan.Marko.Official
    - https://twitter.com/idzanmarko
    - https://www.linkedin.com/in/markoidzan/
    - https://www.youtube.com/channel/UC1E7cbcnFqHEqTYmbZHKDPA
    - https://www.instagram.com/markoidzan/
    - https://www.twitch.tv/idzanmarko
    - https://github.com/idzan

webmaster_verifications:
  google: Nqz4seLf_1h2YSk9z3iTG4aNARiu48Q6mlEmtNpFwWw
  bing: 6E829E71F72385BF19D8107B790FA80D
  yandex: a461b1e3fb30179a

pagination:
  enabled: true
  debug: false
  per_page: 6
  permalink: /page:num/
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

pwa:
  sw_src_filepath: service-worker.js
  sw_dest_filepath: service-worker.js
  dest_js_directory: assets/js
  precache_recent_posts_num: 10
  precache_glov_directory: /
  precache_blog_patterns:
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - "{img}/**/*.{webp,svg,jpg}"
    - index.html
    - offline.html
  precache_glob_ignores:
    - sw-register.js


exclude: [vendor]

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-pwa-workbox
  - jekyll-email-protect
  - jekyll-gist