# Site settings
version: 1534176654523
title:  Marko Idžan
email: marko@idzan.eu
description: > # this means to ignore newlines until "baseurl:"
  Marko Idžan's Official Web Site and Blog
baseurl: "/amp" # the subpath of your site, e.g. /blog
canonical_baseurl: "" # the subpath of your site, e.g. /blog
url: "https://idzan.eu" # the base hostname & protocol for your site
github_username:  idzan

# Build settings
markdown: kramdown
sass:
  style: compressed

destination:   _site/amp
layouts_dir:   ./_layouts-amp
exclude:   [nodemodules, script, Gemfile, npm-debug.log, sw.js, browserconfig.xml, package.json, favicon.ico]

defaults:
  -
    scope:
      path: "_posts"
    values:
layout: "default"