title: Marko Idžan
email: marko@idzan.eu
description: Marko Idžan's Official Web Site and Blog
baseurl: ""
url: "https://idzan.eu"

markdown: kramdown

# Portfolio Collections
collections:
  portfolio:
    output: true
    permalink: /my-works/:path/