backend:
  name: git-gateway
  branch: master
media_foler: 'assets/img'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
#  - name: 'portfolio'
#    label: 'Portfolio'
#    folder: '_projects/'
#    fields:
#      - { name: Title }
